version: '3.3'

networks:
  traefik-net:
    external: true
  couchdb:
    external: true

services:

  master:
    image: dottgonzo/couchbase-for-swarm
    networks:
      - traefik-net
      - couchdb
    environment:
      TYPE: MASTER
      AUTO_REBALANCE: 'true'
      DB_USER: 'maomao'
      DB_PASSW: 'zigozago'
    deploy:
      labels:
        - traefik.port=11211
        - traefik.frontend.rule=Host:couchdb.be-on.tv
        - traefik.docker.network=traefik-net
        - traefik.cluster.port=8091
        - traefik.cluster.frontend.rule=Host:couchadmin.be-on.tv
        - traefik.cluster.docker.network=traefik-net
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 5s

  replicas:
    image: dottgonzo/couchbase-for-swarm
    networks:
      - couchdb
    environment:
      TYPE: WORKER
      COUCHBASE_MASTER: couchdb_master
      AUTO_REBALANCE: 'true'
      DB_USER: 'maomao'
      DB_PASSW: 'zigozago'
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 5s



  watch:
    image: ubuntu
    networks:
      - couchdb
    command: sleep 5d
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 5s











